#pragma once
/**
 * @file ntru_trapgen.h
 * @brief NTRU Trapdoor Generation (TrapGen) — 完整主流程
 *
 * Implements the full NTRU TrapGen algorithm from the IBAGS paper:
 *   1. Sample f, g (short polynomials via discrete Gaussian)
 *   2. Check f is invertible in R_p = Z_q[x]/(x^n+1); re-sample if not
 *   3. Compute f_inv, then h = g * f_inv mod (q, x^n+1)
 *   4. (Optional) Check h is invertible; precompute h_inv if needed
 *   5. Solve NTRU equation f*G - g*F = q (mod x^n+1) to get F, G
 *   6. Assemble TrapdoorBasis B = [[c(f), c(g)], [c(F), c(G)]]
 *   7. Output PublicTrapdoorParams { h, params } and
 *      MasterTrapdoorSecret { f, g, F, G, B, h_inv }
 *
 * Reference:
 *   - Falcon specification §3.1 (f, g sampling and invertibility)
 *   - NTRU key generation (IEEE P1363.1)
 *   - Ducas–Lyubashevsky–Prest (DLP) trapdoor construction
 *
 * Production notes:
 *   - Current NTRU equation solver is a [STUB]: in PoC, stores F, G as zeros
 *     and marks the solver as NOT_FOR_PRODUCTION.
 *   - Production must integrate a full NTRU equation solver (e.g., using
 *     Babai nearest plane on NTRU lattice, or the Falcon-compatible solver).
 *   - Sample-until-invertible loop has configurable max_attempts.
 *   - All secret polynomials are zeroed on destruction (SecretPoly / Poly).
 */

#include "params.h"
#include "poly.h"
#include "secure_memory.h"
#include "csprng.h"
#include "errors.h"

#include <cstddef>
#include <cstdint>
#include <vector>

namespace ibags {

// ============================================================================
// §1  PublicTrapdoorParams — 公钥陷门参数
// ============================================================================

/**
 * @struct PublicTrapdoorParams
 * @brief Public parameters generated by NTRU TrapGen.
 *
 * Contains h = g * f^{-1} mod (q, x^n+1) — the public key component
 * of the NTRU trapdoor.
 */
struct PublicTrapdoorParams {
    Params params;           // Underlying parameter set
    Poly   h;                // h = g * f^{-1} mod (q, x^n+1)
    bool   h_is_invertible;  // True if h_inv was successfully computed
    Poly   h_inv;            // h^{-1} mod (q, x^n+1), only valid if h_is_invertible

    /// Explicit constructor: Poly has no default constructor
    explicit PublicTrapdoorParams(const Params& pp)
        : params(pp), h(pp.n), h_is_invertible(false), h_inv(pp.n) {}
};

// ============================================================================
// §2  TrapdoorBasis — 陷门格基
// ============================================================================

/**
 * @struct TrapdoorBasis
 * @brief 2n × 2n trapdoor basis B = [[c(f), c(g)], [c(F), c(G)]]
 *
 * Each component is stored as a Poly.
 * B is the short basis of the NTRU lattice:
 *   Λ_q(A) = { (y1, y2) ∈ R^2 : y1 + y2*h ≡ 0 mod q }
 *
 * The basis has the property:
 *   B * (1, h)^T = (f + g*h, F + G*h)^T = (0, q)^T
 *   (up to ring operations mod x^n+1)
 */
struct TrapdoorBasis {
    Poly f;   // Secret short polynomial f
    Poly g;   // Secret short polynomial g
    Poly capF; // Secret short polynomial F (solved from NTRU equation)
    Poly capG; // Secret short polynomial G (solved from NTRU equation)

    /// Explicit constructor: Poly has no default constructor
    explicit TrapdoorBasis(int n)
        : f(n), g(n), capF(n), capG(n) {}

    /// Check that all four polynomials have the same dimension
    [[nodiscard]] bool dimensions_consistent() const noexcept;
};

// ============================================================================
// §3  MasterTrapdoorSecret — 主密钥对
// ============================================================================

/**
 * @struct MasterTrapdoorSecret
 * @brief Master trapdoor secret (f, g, F, G) plus precomputed h_inv.
 *
 * OWNERSHIP: This struct owns secret data. Destroy by assigning to a
 * default-constructed instance or letting it go out of scope.
 *
 * The basis B enables Gaussian preimage sampling (GaussSample).
 */
struct MasterTrapdoorSecret {
    TrapdoorBasis basis;   // f, g, F, G
    Poly          h_inv;   // Precomputed h^{-1} for GaussSample (if available)
    bool          h_is_invertible; // True if h_inv is valid

    /// Explicit constructor: Poly and TrapdoorBasis have no default constructor
    explicit MasterTrapdoorSecret(int n)
        : basis(n), h_inv(n), h_is_invertible(false) {}
};

// ============================================================================
// §4  NTRU equation result
// ============================================================================

/**
 * @struct NtruEquationResult
 * @brief Result of solving the NTRU equation f*G - g*F = q.
 */
struct NtruEquationResult {
    Poly F;   // Short solution polynomial F
    Poly G;   // Short solution polynomial G

    /// Aggregate initialization: NtruEquationResult{F_poly, G_poly}
    NtruEquationResult(Poly f_poly, Poly g_poly)
        : F(std::move(f_poly)), G(std::move(g_poly)) {}
};

// ============================================================================
// §5  TrapGen configuration
// ============================================================================

/**
 * @struct TrapGenConfig
 * @brief Configuration for the TrapGen algorithm.
 */
struct TrapGenConfig {
    int  max_invertibility_attempts; // Max f-sampling attempts before failure
    bool compute_h_inv;              // Whether to precompute h^{-1}
    bool fallback_on_ntru_solver;    // If true, allow F=G=0 (stub) on solver failure

    static TrapGenConfig default_config() {
        return { .max_invertibility_attempts = 100,
                 .compute_h_inv              = true,
                 .fallback_on_ntru_solver    = true };
    }

    static TrapGenConfig strict_config() {
        return { .max_invertibility_attempts = 100,
                 .compute_h_inv              = true,
                 .fallback_on_ntru_solver    = false };
    }
};

// ============================================================================
// §6  Sample-until-invertible
// ============================================================================

/**
 * @brief Sample f repeatedly until it is invertible mod q, or max_attempts
 *        is reached.
 *
 * On success, f_out contains the invertible f.
 * On failure, returns TrapdoorError.
 *
 * @param pp          Parameter set
 * @param csprng      Seeded CSPRNG
 * @param max_attempts Maximum sampling attempts
 * @param f_out       [out] Sampled invertible f (only valid if Ok)
 * @return            Ok() or {TrapdoorError, "f not invertible after N attempts"}
 */
[[nodiscard]] Status sample_f_until_invertible(const Params& pp,
                                                SeedCSPRNG& csprng,
                                                int max_attempts,
                                                Poly* f_out);

// ============================================================================
// §7  NTRU TrapGen main
// ============================================================================

/**
 * @brief Execute full NTRU TrapGen.
 *
 * Steps:
 *   1. Sample f until invertible (→ f_out)
 *   2. Sample g (→ g_out)
 *   3. Compute f_inv
 *   4. Compute h = g * f_inv
 *   5. Optionally compute h_inv
 *   6. Solve NTRU equation (stub → F=G=0 for PoC)
 *   7. Assemble TrapdoorBasis
 *
 * @param pp          Parameter set
 * @param csprng      Seeded CSPRNG
 * @param config      TrapGen configuration
 * @param pub_out     [out] Public trapdoor parameters (h, params)
 * @param sec_out     [out] Master trapdoor secret (f, g, F, G, B, h_inv)
 * @return            Ok() or error status
 */
[[nodiscard]] Status ntru_trapgen(const Params& pp,
                                   SeedCSPRNG& csprng,
                                   const TrapGenConfig& config,
                                   PublicTrapdoorParams* pub_out,
                                   MasterTrapdoorSecret* sec_out);

// ============================================================================
// §8  NTRU equation solver
// ============================================================================

/**
 * @brief Solve the NTRU equation: find short F, G such that
 *        f*G - g*F = q  (mod x^n+1)
 *
 * [STUB - NOT FOR PRODUCTION]
 * Current implementation returns F=G=0 (zero polynomials).
 *
 * Production must implement one of:
 *   - Falcon-style NTRU equation solver (field norm method)
 *   - Babai nearest plane on the NTRU lattice
 *   - Gentry-Peikert-Vaikuntanathan (GPV) trapdoor solver
 *
 * @param pp        Parameter set
 * @param f         Short polynomial f
 * @param g         Short polynomial g
 * @param result    [out] F, G solution (zeroed on failure)
 * @return          Ok() or SamplingError if stub disallowed
 */
[[nodiscard]] Status solve_ntru_equation(const Params& pp,
                                          const Poly& f,
                                          const Poly& g,
                                          NtruEquationResult* result);

// ============================================================================
// §9  TrapdoorBasis verification
// ============================================================================

/**
 * @brief Verify NTRU trapdoor relation: h == g * f^{-1} mod (q, x^n+1).
 *
 * @param pp   Parameter set
 * @param f    Secret f
 * @param g    Secret g
 * @param h    Public h
 * @return     true iff h * f == g mod (q, x^n+1)
 */
[[nodiscard]] bool check_h_from_f_g(const Params& pp,
                                     const Poly& f,
                                     const Poly& g,
                                     const Poly& h);

/**
 * @brief Full TrapdoorBasis validation.
 *
 * Checks:
 *   1. All four polys have consistent dimension
 *   2. f, g, F, G infinity norms are within Params::eta1
 *   3. h == g * f^{-1} (via check_h_from_f_g)
 *   4. B canonical form (all coefficients in [0, q))
 *   5. (If f, g, F, G non-trivial) NTRU relation: f*G - g*F == q mod (x^n+1)
 *
 * @param pp     Parameter set
 * @param basis  The trapdoor basis to verify
 * @param h      Public h (for relation check)
 * @return       true iff all checks pass
 */
[[nodiscard]] bool check_trapdoor_basis(const Params& pp,
                                         const TrapdoorBasis& basis,
                                         const Poly& h);

// ============================================================================
// §10  GaussSample stub
// ============================================================================

/**
 * @brief Preimage sampling from the trapdoor basis (GaussSample).
 *
 * Given a target t ∈ R_p and the trapdoor basis B, sample a short
 * preimage (s1, s2) such that s1 + s2*h ≡ t (mod q, x^n+1).
 *
 * [STUB - NOT FOR PRODUCTION]
 * Current implementation returns zero vectors.
 *
 * Production must implement:
 *   - Falcon-style fast Fourier nearest plane
 *   - GPV-style discrete Gaussian sampler over the NTRU lattice
 *   - Or DDLL-style randomized Babai rounding
 *
 * @param pp      Parameter set
 * @param basis   Trapdoor basis B = [[c(f), c(g)], [c(F), c(G)]]
 * @param target  Target polynomial t ∈ R_p
 * @param sigma   Gaussian width (from Params::sigma)
 * @param csprng  Seeded CSPRNG for entropy
 * @param s1_out  [out] First half of preimage
 * @param s2_out  [out] Second half of preimage
 * @return        Ok() or SamplingError
 */
[[nodiscard]] Status gauss_sample_preimage(const Params& pp,
                                            const TrapdoorBasis& basis,
                                            const Poly& target,
                                            double sigma,
                                            SeedCSPRNG& csprng,
                                            Poly* s1_out,
                                            Poly* s2_out);

} // namespace ibags